### ISSUE TITLE
New processes running in background after USR2

### ISSUE THREAD

**Issue by olizax** [facebookgo/grace#11]
After received USR2, the new processes will run in background, in that case, supervisord (A Process Control System)  can't  track the new processes. Is there any chance to add an option to force the new processes run in foreground?

**Comment by daaku** [comment]
For various reasons including how the Go runtime behaves, we must start a new process and let the old one die. There is a strategy that may work, which requires 2 restarts. It's implemented by another library that does graceful restarts called goagain: https://github.com/rcrowley/goagain (it's their `Double` strategy). We're not planning on adding such a feature to grace.
