### ISSUE TITLE
Configurable `StopTimeout` and `KillTimeout`

### ISSUE THREAD

**Issue by jingweno** [facebookgo/grace#19]
It will be nice to be able to configure `StopTimeout` and `KillTimeout` for `gracehttp`: https://github.com/facebookgo/grace/blob/master/gracehttp/http.go#L41.

**Comment by daaku** [comment]
For pretty much anything besides the simplest of use cases it's better to use the underlying libraries. I want to keep the `gracehttp` layer very small.
