### ISSUE TITLE
Gracedemo process only restarts once

### ISSUE THREAD

**Issue by nkev** [facebookgo/grace#20]
Gracedemo process only restarts once:

1) gracedemo
2) curl 'http://localhost:48567/sleep/?duration=30s'
3) kill -USR2 $GRACEDEMOPID
4) observe proper graceful restart; curl 'http://localhost:48567/sleep/?duration=1s' works fine
5) kill -USR2 $GRACEDEMOPID_NEW
6) gracedemo process terminates instead of restarting again

Macbook Pro 10.11 El Capitan, Go 1.5.1

**Comment by daaku** [comment]
Just tried it on 10.11 El Capitan, Go 1.5.1:

```
naitik ✇ hactar ~ gracedemo  
2015/10/11 10:46:00 Serving [::]:48567, [::]:48568, [::]:48569 with pid 53209
2015/10/11 10:46:40 Graceful handoff of [::]:48567, [::]:48568, [::]:48569 with new pid 53273 and old pid 53209
2015/10/11 10:46:49 Graceful handoff of [::]:48567, [::]:48568, [::]:48569 with new pid 53275 and old pid 53273
2015/10/11 10:46:49 Exiting pid 53273.
```

Are you sure you used the right pids? Sounds like in step 5 you used the original pid instead of the new pid.

**Comment by matthewmueller** [comment]
For anyone running into this issue and getting confused, you you have build your binary. 

For some reason `go run gracedemo.go` will only restart once, but `go build gracedemo.go && ./gracedemo` works indefinitely.
