### ISSUE TITLE
how to grace restart webscoket  server without disconnection the connection 

### ISSUE THREAD

**Issue by xuxiangyang** [facebookgo/grace#24]
Hi， I have a  question. How could I grace restart the websocket server without  disconnection the connection. 

I need some help, Thx~

**Comment by daaku** [comment]
Unfortunately the way websockets work doesn't interact well with https://golang.org/pkg/net/http/#ConnState which is what `grace` (and `httpdown` underneath) relies on to detect when a connection has been closed. So if you want to graceful shutdown support for websockets you'll need to handle it outside of `grace` (maybe using `gracenet` directly).
