### ISSUE TITLE
How to use https api ListenAndServeTLS

### ISSUE THREAD

**Issue by lovelly** [facebookgo/grace#31]
How to use https api ListenAndServeTLS

**Comment by daaku** [comment]
You'll need to pass in a valid `tls.Config` in the `http.Server` you pass to `gracehttp.Serve`:

https://golang.org/pkg/crypto/tls/#Config
https://golang.org/pkg/net/http/#Server
https://godoc.org/github.com/facebookgo/grace/gracehttp#Serve
