### ISSUE TITLE
Use semver and git tag ?

### ISSUE THREAD

**Issue by AaronO** [facebookgo/grace#32]
Hi first of all thanks for building `grace`,

I was wondering if you had though about tagging and releasing `semver` versions of `grace` ? 

Shipping semver releases makes it easy for users of the library to use a specific version and not be affected by accidental breaking changes (this can always be done by using an explicit SHA, but a semver tag is arguably nicer).

**Comment by daaku** [comment]
Since we don't use semver or tags ourselves promising to maintain those becomes overhead/afterthought so we don't tend to have those on any of our packages. (We vendor everything.)
